### ISSUE TITLE
Doesn't seem to properly report failures?

### ISSUE THREAD

**Issue by drj17** [sorry-cypress/cy2#3] opened 2021-04-23 20:40 UTC
Apologies if this is unrelated, but it only started happening when we switched to using cy2 in our github action.

In our integration-tests.yml file:
```
 - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn api, yarn start:test
          wait-on: 'http://localhost:3000, http://localhost:8081/cypress'
          wait-on-timeout: 120
          install: false
          group: 'E2E Tests'
          command: yarn cy2 run --parallel --record'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_API_URL: https://<app-name>.herokuapp.com
```

We have a cypress test that _is_ failing, but in github it says that all checks are passing.
![Screen Shot 2021-04-23 at 4 35 00 PM](https://user-images.githubusercontent.com/13426126/115927057-dbb04280-a451-11eb-801c-8c2c1e17e9b6.png)

![Screen Shot 2021-04-23 at 4 40 23 PM](https://user-images.githubusercontent.com/13426126/115927552-9b9d8f80-a452-11eb-8b58-7fcf5ff05954.png)

**Comment by agoldis** [comment] 2021-04-23 23:01
Interesting... 

1. is it reproducible without `cy2` - i.e. manually changing [cypress configuration](https://docs.sorry-cypress.dev/cypress-agent/configuring-cypress-agent)?
2. 
2. are you using sorry-cypress github hooks integration? May be it's a bug in hooks implementation

**Comment by drj17** [comment] 2021-04-25 22:16
I'll check trying it without cy2 sometime this week.  It was a little tough because I have to figure out where it's installed in the action, so in the interest of saving minutes I just went with `cy2` 😄  For your other point though, we _are_ using the github integration, and for that one it _never_ reports successfully.  Once all tests have passed our status check still says "Expected" and never finishes. 

<img width="857" alt="Screen Shot 2021-04-25 at 6 11 33 PM" src="https://user-images.githubusercontent.com/13426126/116011311-52844180-a5f2-11eb-9c4c-95c4fb5f1f17.png">
<img width="418" alt="Screen Shot 2021-04-25 at 6 13 59 PM" src="https://user-images.githubusercontent.com/13426126/116011312-52844180-a5f2-11eb-9d2c-2ed6dbbaa0e9.png">

**Comment by drj17** [comment] 2021-04-26 16:55
Okay, it might be two separate issues here.   I _was_ able to get it to fail when I manually changed the cypress configuration.  However, the github hook still never updates for me.

**Comment by agoldis** [comment] 2021-04-26 17:08
Thanks for sharing the details @drj17!

Those indeed look like two different problems. In theory `cy2` shouldn't change how failures are reported / identified - it just a thin `cypress` wrapper that changes the API endpoint.

What SC version are you running? 

## For runs falsely reported as "passed"

Let's distinguish between different types of reports, please let me know if a failed test appears as failed:
- while running `cy2`
- marked as failed in DB
- appears as failed in SC dashboard
- reported as failed to GH

## For missing status updates in GH

There's an ongoing issue with how we detect finished runs - it's been tracked https://github.com/sorry-cypress/sorry-cypress/issues/299. Are you using redis for tracking inactivity timeout?

**Comment by renanvalentin** [comment] 2021-04-28 20:42
Hello, i'm facing the same issue;

Looks like the script doesn't exit with status 1.

I did this as a workaround:

```javascript
yarn run:ci --tag "e2e,branch-$BITBUCKET_BRANCH" | tee  >(grep -Ec '([1-9][0-9]?)+\sfailing' > result)

if [ "$(cat result)" -ge 1 ]
then

    echo "Exit 1"

    exit 1

else

    echo "Exit 0"

    exit 0

fi
```

**Comment by agoldis** [comment] 2021-04-30 20:33
@drj17  I am closing the issue for now, it doesn't seem like `cy2` is the problem, please consider re-opening the issue in https://github.com/sorry-cypress/sorry-cypress and attach more data. 

**For runs falsely reported as "passed"**
- Please provide more information by filing a new issue on https://github.com/sorry-cypress/sorry-cypress.

**Missing status updates on Github**
- Github status update is not related to `cy2`, there's an ongoing issue, which is been tracked at sorry-cypress/sorry-cypress#299

--- 

@renanvalentin I am opening a new issue, your report is valid, but not related this one.

**Closed by agoldis** 2021-04-30 20:33 UTC
